name: Hello world
on: workflow_dispatch
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Build Step
       run: echo "a demo build"
 
 test:
     runs-on: ubuntu-latest
     steps:
       - name: Test Phase
         run: echo "running in test phase"

 deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy phase
        run: "welcome to deploy phase"
        
        
   
        
